### ISSUE TITLE
Unexpected EOF when scanning a QR code that contains a newline character

### ISSUE THREAD

**Issue by nfaucher8** [InfinitePeripherals/QuantumSDK-Cordova#1]
I have been using QuantumSDK-Cordova with a LineaPro11 device and I have found that when I scan a QR code that contains a newline character I get a `SyntaxError: Unexpected EOF` error. I have tested QR codes that don't contain a newline character and they don't produce the error.

I have included the two QR codes I have been using so that this error can be reproduced.

![single](https://github.com/InfinitePeripherals/QuantumSDK-Cordova/assets/64989612/c9395b99-8275-4fa3-ba5c-cd50b584894b)
This QR code contains a payload of:
```
line1
```
and does not produce any error when scanned

![multi](https://github.com/InfinitePeripherals/QuantumSDK-Cordova/assets/64989612/e2f0a182-caa4-4cee-bea9-e5d8ef07996d)
This QR code contains a payload of:
```
line1
line2
```
and does produce the `SyntaxError: Unexpected EOF` error when scanned

It seems like the error comes from https://github.com/InfinitePeripherals/QuantumSDK-Cordova/blob/main/src/ios/QuantumSDKCordova.m#L80

I have been using the `barcodeDecimals` callback instead of `barcodeData` because it wasn't getting called. I think this error could possibly be the reason why.

This stackoverflow post also might be relevant, https://stackoverflow.com/questions/11478324/syntaxerror-unexpected-eof-when-evaluating-javascript-in-ios-uiwebview/22810989#22810989

**Additional info:**
Device: LineaPro11
Firmware: 5.69.51
iOS: 17.1.1

**Comment by IPCLorenz** [comment]
Thank you for the report.

Our developer fixed the issue and updated the repo.
